---
 environment: production
 chdir: /Users/juergen/dev/storyteller
 address: 0.0.0.0
 user: root
 group: root
 port: 80
 pid: /Users/juergen/dev/storyteller/log/thin.pid
 rackup: /Users/juergen/dev/storyteller/config.ru
 log: /Users/juergen/dev/storyteller/log/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: true