---
 environment: production
 chdir: /var/www/juergenalbertsen.de
 address: 0.0.0.0
 user: root
 group: root
 port: 80
 pid: log/thin.pid
 rackup: config.ru
 log: log/thin.log
 max_conns: 1024
 timeout: 30
 max_persistent_conns: 512
 daemonize: true
