#!/bin/bash

INPUT=$1

if [ -z "$INPUT" ] ; then
	echo "Usage: $0 <input>"
	exit 1
fi

OUTPUT=${INPUT%%.*}.md
TEMP=$OUTPUT.temp

echo "Converting $INPUT -> $OUTPUT"

pandoc -f html -t markdown -o $TEMP < $INPUT
sed "s/^\\\\/---/g" < $TEMP > $OUTPUT

rm -f $TEMP
