#!/bin/sh
### BEGIN INIT INFO
# Provides:          thin
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: thin initscript
# Description:       thin
### END INIT INFO

# Original author: Forrest Robertson

# Do NOT "set -e"

THIN=/usr/local/bin/thin
BUNDLE=/usr/local/bin/bundle
SCRIPT_NAME=/etc/init.d/thin
CONFIG_PATH=/etc/thin
APP_PATH=/var/www/juergenalbertsen.de

case "$1" in
  start)
	cd $APP_PATH && $BUNDLE $THIN start --all $CONFIG_PATH
	;;
  stop)
	cd $APP_PATH && $BUNDLE $THIN stop --all $CONFIG_PATH
	;;
  restart)
	cd $APP_PATH && $BUNDLE $THIN restart --all $CONFIG_PATH
	;;
  *)
	echo "Usage: $SCRIPT_NAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
