development: &defaults
  adapter: mysql
  encoding: utf8
  host: localhost
  database: storyteller_dev
 
test:
  database: storyteller_test
  <<: *defaults
 
production:
  database: storyteller
  username: storyteller
  <<: *defaults